### ISSUE TITLE
Error when Training ContrasTR on BDD100K: Unexpected Keyword Argument 'skip_tracking_head'

### ISSUE THREAD

**Issue by JJIN-1916** [pfdp0/ContrasTR#1]
Hello ContrasTR team,

I encountered an error while attempting to train ContrasTR on the BDD100K dataset, following the instructions in the README. 
The error message is as follows:

`TypeError: ContrasTR.forward() got an unexpected keyword argument 'skip_tracking_head'`

Upon tracing the code, I noticed that the forward method in ContrasTR does not include a `skip_tracking_head` parameter. 
It appears that this argument is being passed but not expected by the model.

Could you advise on how to resolve this issue? Any guidance would be greatly appreciated. 
Thank you!

<img width="991" alt="image" src="https://github.com/user-attachments/assets/3833668f-d473-4f24-933e-be2de76e3350">

**Comment by pfdp0** [comment]
Dear ELLIE,

Thank you for letting us know! 
the bug is now fixed, so all you have to do is pull the last commit.

**Comment by JJIN-1916** [comment]
Thank you for your prompt response and support.

While reviewing the recent updates after pulling the latest changes, I have a quick question for confirmation. 
In the `models/ops/functions/ms_deform_attn_func.py` file, I previously modified the `forward` function of the `MSDeformAttnFunction` class to cast `value` from float16 to float. 

With the newly added `@custom_fwd(cast_inputs=torch.float32)` decorator, 
does this now ensure that all input parameters for the forward function are cast to float32?? 

And I have confirmed that the training is working! Thank you for addressing the issue! 👍👍👍

**Comment by nicolamarinello** [comment]
> Thank you for your prompt response and support.
> 
> While reviewing the recent updates after pulling the latest changes, I have a quick question for confirmation. In the `models/ops/functions/ms_deform_attn_func.py` file, I previously modified the `forward` function of the `MSDeformAttnFunction` class to cast `value` from float16 to float.
> 
> With the newly added `@custom_fwd(cast_inputs=torch.float32)` decorator, does this now ensure that all input parameters for the forward function are cast to float32??
> 
> And I have confirmed that the training is working! Thank you for addressing the issue! 👍👍👍

Yes, correct.
